% SUBJNAMES Lists all the subject names as a cell array of strings

function names = subjnames()

% DECLARATIONS ------------------------------------------------------------
% Declare list of existant subject names
names = {...
    'Dog_1', ...
    'Dog_2', ...
    'Dog_3', ...
    'Dog_4', ...
    'Dog_5', ...
    'Patient_1', ...
    'Patient_2'  ...
    };

end